# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: mansimladdha@gmail.com
author_name: mansi754
preset_name: starter
project_name: Ip_tokenization-frontend

